- name: Synchronize globally installed packages
  become: true
  ansible.builtin.apt:
    pkg:
      - curl
      - micro
      - git
      - openssh-server
      - openssh-client
      - kitty-terminfo
      - ripgrep
      - eza
      - bat
      - btop
      - hyfetch
      - python3
      - python3.12-venv
      - fish
      - zsh
      - bash
      - gcc
      - g++
      - clang
      - vim
      - neovim
      - emacs
    state: latest
    update_cache: yes
    cache_valid_time: 3600
