- name: Synchronize reednet computers
  hosts: all
  tasks:
    - name: Ensure SSH accepts env vars
      become: true
      ansible.builtin.copy:
        content: |
          AcceptEnv COLORTERM
          AcceptEnv DARKMODE
        dest: '/etc/ssh/sshd_config.d/10-sam-accept-env.conf'
        group: 'root'
        mode: '644'
        owner: 'root'

    - name: Set system flake registry
      become: true
      ansible.builtin.copy:
        src: './registry.json'
        dest: '/etc/nix/registry.json'
        owner: 'root'
        group: 'root'
        mode: '644'

    - name: Delete Polly's TLS cert from trusted store.
      become: true
      ansible.builtin.file:
        path: '/usr/local/share/ca-certificates/polly.reed.edu.crt'
        state: 'absent'

    - name: Delete Patty's TLS cert from trusted store.
      become: true
      ansible.builtin.file:
        path: '/usr/local/share/ca-certificates/patty.reed.edu.crt'
        state: 'absent'

    - name: Update CA certs.
      become: true
      ansible.builtin.command: 'update-ca-certificates'

    # If we need custom certs again, Firefox needs them specially configured here.
    - name: Ensure /etc/firefox/policies exists.
      become: true
      ansible.builtin.file:
        path: '/etc/firefox/policies/'
        state: 'directory'
        owner: 'root'
        group: 'root'
        mode: '0755'

    - name: Install TLS certs to a Firefox-readable directory.
      become: true
      ansible.builtin.file:
        path: '/etc/firefox/certs'
        state: 'absent'

    # Do nothing for now.
    - name: Set Firefox policies.json
      become: true
      ansible.builtin.copy:
        dest: '/etc/firefox/policies/policies.json'
        group: 'root'
        owner: 'root'
        mode: '644'
        content: |
          {
            "policies": {}
          }

    # Synchronize globally installed packages
    - import_tasks: packages.yaml

    # Synchronize users
    - import_tasks: users.yaml
