- name: Synchronize reednet computers
  hosts: reednet
  tasks:
    - name: Ensure SSH accepts env vars
      become: true
      ansible.builtin.copy:
        content: |
          AcceptEnv COLORTERM
          AcceptEnv DARKMODE
        dest: '/etc/ssh/sshd_config.d/10-sam-accept-env.conf'
        group: 'root'
        mode: '644'
        owner: 'root'

    - name: Set system flake registry
      become: true
      ansible.builtin.copy:
        src: './registry.json'
        dest: '/etc/nix/registry.json'
        owner: 'root'
        group: 'root'
        mode: '644'


    # Synchronize globally installed packages
    - import_tasks: packages.yaml

    # Synchronize users
    - import_tasks: users.yaml

        

    # falcon
    # nix
    # tailscale
    # motd
    # /etc/hosts
